use std::collections::BTreeMap;

use futures_channel::oneshot::Sender;
use glam::{DVec2, FloatExt};
use wasm_bindgen::prelude::*;

use crate::{anim_data::flatten_bones, editor::Editor, entity::mine::Mine, grid::{COLS, Grid, ROWS}, map_file::MapFile, ninja::{Ninja, NinjaState, PastNinja}, orientation::OrientationExt, segment::{Segment, extract_path}, simulation::{Input, KeyFrame, Simulation}, tile::TILE_SIZE};

#[wasm_bindgen]
pub struct Replay {
    pub(crate) _level_name: String,
    pub(crate) _author_name: Option<String>,
    pub(crate) segments: Grid<Segment>,
    pub(crate) inputs: Vec<u8>,
    pub(crate) past_ninjas: Vec<PastNinja>,
    pub(crate) initial_mines: Vec<Mine>,
    pub(crate) current_sim: Simulation,
    pub(crate) preview_sim: Simulation,
    pub(crate) keyframes: BTreeMap<u32, KeyFrame>,
    pub(crate) sender: Option<Sender<Vec<PastNinja>>>,
    pub(crate) anim_data: Box<[u8]>,
}

#[wasm_bindgen]
impl Replay {
    pub fn send_past_ninjas(&mut self) {
        if let Some(sender) = self.sender.take() {
            let _ = sender.send(std::mem::take(&mut self.past_ninjas));
        }
    }

    pub fn set_input(&mut self, jump: bool, right: bool, left: bool, suicide: bool) {
        if self.current_sim.frame == self.inputs.len() as u32 {
            if self.current_sim.frame >= 5 * 60 * 60 {
                // limit max input length to five minutes because I don't want to use too much memory
                return;
            }
            self.inputs.push(Input::new(jump, right, left, suicide).into_byte());

            // Invalidate any state that were generated by preview seek into the future
            self.past_ninjas.truncate(self.current_sim.frame as usize);
            if self.preview_sim.frame > self.current_sim.frame {
                self.preview_sim = self.current_sim.clone();
            }
        } else if let Some(&old_input) = self.inputs.get(self.current_sim.frame as usize) {
            let new_input = Input::new(jump, right, left, suicide).into_byte();
            if new_input != old_input {
                // Invalidate future keyframes
                self.keyframes.retain(|&frame, _| frame == 0 || frame < self.current_sim.frame);
                self.inputs[self.current_sim.frame as usize] = new_input;
                self.preview_sim = self.current_sim.clone();
                self.past_ninjas.truncate(self.current_sim.frame as usize);
            }
        }
    }

    pub fn tick(&mut self) {
        if (self.current_sim.frame as usize) < self.inputs.len() {
            // Save keyframe every 120 frames
            if self.current_sim.frame.is_multiple_of(120) && !self.keyframes.contains_key(&self.current_sim.frame) {
                self.keyframes.insert(self.current_sim.frame, KeyFrame::from_sim(&self.current_sim, &self.initial_mines));
            }

            if let Some(past_ninja) = self.past_ninjas.get_mut(self.current_sim.frame as usize) {
                *past_ninja = self.current_sim.ninja.to_past_ninja();
            } else if self.current_sim.frame as usize == self.past_ninjas.len() {
                self.past_ninjas.push(self.current_sim.ninja.to_past_ninja());
            } else {
                #[cfg(debug_assertions)]
                panic!("past_ninja vec is shorter than expected");
            }

            let input = Input::from_byte(self.inputs[self.current_sim.frame as usize]);
            self.current_sim.tick(input, &self.segments);

            #[cfg(debug_assertions)]
            assert!(self.current_sim.frame <= self.past_ninjas.len() as u32);
        }
    }

    /// Seek until self.current_sim reaches target_frame
    pub fn seek(&mut self, target_frame: u32) {
        let target_frame = target_frame.min(self.inputs.len() as u32);
        // TODO: can use upper_bound method to get closest_keyframe once btree_cursors feature is stabilized.
        // This current filter then max alternative isn't very efficient, but oh well.
        let closest_keyframe = self.keyframes.keys().filter(|&&f| f <= target_frame).max().expect("keys should always have a key 0, so they should never be empty.");
        if target_frame < self.current_sim.frame || *closest_keyframe > self.current_sim.frame {
            // closest keyframe is better to seek from than current sim, so replace current sim with closest keyframe
            let keyframe = self.keyframes.get(closest_keyframe).expect("failed to get closest keyframe");
            keyframe.hydrate_into(&mut self.current_sim, &self.initial_mines);
        }
        // While loop should always terminate because target_frame has been bound
        // to be at most equal to self.inputs.len()
        while self.current_sim.frame < target_frame {
            self.tick();
        }
    }

    /// Seek until self.preview_sim reaches target_frame
    pub fn seek_preview(&mut self, target_frame: u32) {
        // TODO: can use upper_bound method to get closest_keyframe once btree_cursors feature is stabilized.
        // This current filter then max alternative isn't very efficient, but oh well.
        let closest_keyframe = self.keyframes.keys().filter(|&&f| f <= target_frame).max().expect("keys should always have a key 0, so they should never be empty.");
        if target_frame < self.preview_sim.frame || *closest_keyframe > self.preview_sim.frame {
            // closest keyframe is better to seek from than preview sim, so replace preview sim with closest keyframe
            let keyframe = self.keyframes.get(closest_keyframe).expect("failed to get closest keyframe");
            keyframe.hydrate_into(&mut self.preview_sim, &self.initial_mines);
        }
        while self.preview_sim.frame < target_frame && self.preview_sim.ninja.state != NinjaState::Dead {
            self.tick_preview();
        }
    }

    /// Clear all input history and move ninja to a specific position.
    /// Entity state does not reset.
    pub fn place_ninja(&mut self, x: f64, y: f64) {
        // Clamp x and y to playable area.
        // 0th row and col are always filled with walls.
        let x = x.clamp(TILE_SIZE, TILE_SIZE * (1 + COLS) as f64);
        let y = y.clamp(TILE_SIZE, TILE_SIZE * (1 + ROWS) as f64);
        self.inputs.clear();
        self.keyframes.clear();
        self.current_sim.frame = 0;
        self.current_sim.ninja = Ninja::new(DVec2::new(x, y), OrientationExt::N);
        self.keyframes.insert(0, KeyFrame::from_sim(&self.current_sim, &self.current_sim.entities.mines));
        self.initial_mines = self.current_sim.entities.mines.clone();
        self.preview_sim = self.current_sim.clone();
        self.past_ninjas = vec![self.current_sim.ninja.to_past_ninja()];
    }

    pub fn replay_length(&self) -> u32 {
        self.inputs.len() as u32
    }

    pub fn progress(&self) -> u32 {
        self.current_sim.frame
    }

    pub fn progress_preview(&self) -> u32 {
        self.preview_sim.frame
    }

    pub fn score(&self) -> u32 {
        self.current_sim.score
    }

    pub fn tiles_path(&self) -> String {
        extract_path(&self.segments, true)
    }

    pub fn ninja_x(&self, partial_frame: f64) -> f64 {
        self.current_sim.ninja.pos_old.x.lerp(self.current_sim.ninja.pos.x, partial_frame)
    }

    pub fn ninja_y(&self, partial_frame: f64) -> f64 {
        self.current_sim.ninja.pos_old.y.lerp(self.current_sim.ninja.pos.y, partial_frame)
    }

    pub fn ninja_preview_x(&self, partial_frame: f64) -> f64 {
        self.preview_sim.ninja.pos_old.x.lerp(self.preview_sim.ninja.pos.x, partial_frame)
    }

    pub fn ninja_preview_y(&self, partial_frame: f64) -> f64 {
        self.preview_sim.ninja.pos_old.y.lerp(self.preview_sim.ninja.pos.y, partial_frame)
    }

    pub fn ninja_bones(&self, partial_frame: f64) -> Box<[f64]> {
        let prev = &self.past_ninjas[self.current_sim.frame.saturating_sub(1) as usize];
        flatten_bones(&self.current_sim.ninja.calc_ninja_position(prev, partial_frame, &self.anim_data))
    }

    pub fn ninja_preview_bones(&self, partial_frame: f64) -> Box<[f64]> {
        let prev = &self.past_ninjas[self.current_sim.frame.saturating_sub(1) as usize];
        flatten_bones(&self.preview_sim.ninja.calc_ninja_position(prev,partial_frame, &self.anim_data))
    }

    pub fn past_ninjas_len(&self) -> usize {
        self.past_ninjas.len()
    }

    pub fn past_ninja_x(&self, i: usize) -> f64 {
        self.past_ninjas[i].pos.x
    }

    pub fn past_ninja_y(&self, i: usize) -> f64 {
        self.past_ninjas[i].pos.y
    }

    pub fn past_ninja_bones(&self, i: isize) -> Box<[f64]> {
        if i < 0 || i >= self.past_ninjas.len() as isize || i > self.inputs.len() as isize {
            Box::new([])
        } else {
            flatten_bones(&self.past_ninjas[i as usize].calc_ninja_position(&self.anim_data))
        }
    }

    pub fn inputs_len(&self) -> usize {
        self.inputs.len()
    }

    pub fn input(&self, i: isize) -> u8 {
        self.inputs.get(i as usize).cloned().unwrap_or_default()
    }

    pub fn mines_len(&self) -> usize {
        self.current_sim.entities.mines.len()
    }

    pub fn mine_x(&self, i: usize) -> f64 {
        self.current_sim.entities.mines[i].pos.x
    }

    pub fn mine_y(&self, i: usize) -> f64 {
        self.current_sim.entities.mines[i].pos.y
    }

    pub fn mine_state(&self, i: usize) -> u8 {
        use crate::entity::mine::MineState::*;
        match self.current_sim.entities.mines[i].state {
            Toggled => 0,
            Untoggled => 1,
            Toggling => 2,
        }
    }

    pub fn golds_len(&self) -> usize {
        self.current_sim.entities.golds.len()
    }

    pub fn gold_x(&self, i: usize) -> f64 {
        self.current_sim.entities.golds[i].pos.x
    }

    pub fn gold_y(&self, i: usize) -> f64 {
        self.current_sim.entities.golds[i].pos.y
    }

    pub fn gold_collected(&self, i: usize) -> bool {
        self.current_sim.entities.golds[i].collected
    }

    pub fn bounce_blocks_len(&self) -> usize {
        self.current_sim.entities.bounce_blocks.len()
    }

    pub fn bounce_block_x(&self, i: usize, partial_frame: f64) -> f64 {
        let bounce_block = &self.current_sim.entities.bounce_blocks[i];
        bounce_block.pos_old.x.lerp(bounce_block.pos.x, partial_frame)
    }

    pub fn bounce_block_y(&self, i: usize, partial_frame: f64) -> f64 {
        let bounce_block = &self.current_sim.entities.bounce_blocks[i];
        bounce_block.pos_old.y.lerp(bounce_block.pos.y, partial_frame)
    }

    pub fn bounce_block_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.bounce_blocks[i].orientation.rotation_deg()
    }

    pub fn one_ways_len(&self) -> usize {
        self.current_sim.entities.one_ways.len()
    }

    pub fn one_way_x(&self, i: usize) -> f64 {
        self.current_sim.entities.one_ways[i].pos.x
    }

    pub fn one_way_y(&self, i: usize) -> f64 {
        self.current_sim.entities.one_ways[i].pos.y
    }

    pub fn one_way_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.one_ways[i].orientation.rotation_deg()
    }

    pub fn boost_pads_len(&self) -> usize {
        self.current_sim.entities.boost_pads.len()
    }

    pub fn boost_pad_x(&self, i: usize) -> f64 {
        self.current_sim.entities.boost_pads[i].pos.x
    }

    pub fn boost_pad_y(&self, i: usize) -> f64 {
        self.current_sim.entities.boost_pads[i].pos.y
    }

    pub fn boost_pad_deg(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.boost_pads[i].rotation(partial_frame).to_degrees()
    }

    pub fn boost_pad_anim_progress(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.boost_pads[i].eased_animation_progress(partial_frame)
    }

    pub fn exit_doors_len(&self) -> usize {
        self.current_sim.entities.exits.len()
    }

    pub fn exit_door_x(&self, i: usize) -> f64 {
        self.current_sim.entities.exits[i].door_pos.x
    }

    pub fn exit_door_y(&self, i: usize) -> f64 {
        self.current_sim.entities.exits[i].door_pos.y
    }

    pub fn exit_anim_progress(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.exits[i].eased_animation_progress(partial_frame)
    }

    pub fn exit_switch_x(&self, i: usize) -> f64 {
        self.current_sim.entities.exits[i].switch_pos.x
    }

    pub fn exit_switch_y(&self, i: usize) -> f64 {
        self.current_sim.entities.exits[i].switch_pos.y
    }

    pub fn thwumps_len(&self) -> usize {
        self.current_sim.entities.thwumps.len()
    }

    pub fn thwump_x(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.thwumps[i].x(partial_frame)
    }

    pub fn thwump_y(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.thwumps[i].y(partial_frame)
    }

    pub fn thwump_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.thwumps[i].orientation.rotation_deg()
    }

    pub fn launch_pads_len(&self) -> usize {
        self.current_sim.entities.launch_pads.len()
    }

    pub fn launch_pad_x(&self, i: usize) -> f64 {
        self.current_sim.entities.launch_pads[i].pos.x
    }

    pub fn launch_pad_y(&self, i: usize) -> f64 {
        self.current_sim.entities.launch_pads[i].pos.y
    }

    pub fn launch_pad_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.launch_pads[i].orientation.rotation_deg()
    }

    pub fn floor_guards_len(&self) -> usize {
        self.current_sim.entities.floor_guards.len()
    }

    pub fn floor_guard_x(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.floor_guards[i].x(partial_frame)
    }

    pub fn floor_guard_y(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.floor_guards[i].y(partial_frame)
    }

    pub fn floor_guard_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.floor_guards[i].orientation.rotation_deg()
    }

    pub fn locked_doors_len(&self) -> usize {
        self.current_sim.entities.doors.locked.len()
    }

    pub fn locked_door_x(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.locked[i].pos.x
    }

    pub fn locked_door_y(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.locked[i].pos.y
    }

    pub fn locked_door_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.locked[i].orientation.rotation_deg()
    }

    pub fn locked_door_anim_progress(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.doors.locked[i].eased_animation_progress(partial_frame)
    }

    pub fn locked_switch_x(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.locked[i].switch_pos.x
    }

    pub fn locked_switch_y(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.locked[i].switch_pos.y
    }

    pub fn trap_doors_len(&self) -> usize {
        self.current_sim.entities.doors.trap.len()
    }

    pub fn trap_door_x(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.trap[i].pos.x
    }

    pub fn trap_door_y(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.trap[i].pos.y
    }

    pub fn trap_door_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.trap[i].orientation.rotation_deg()
    }

    pub fn trap_door_anim_progress(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.doors.trap[i].eased_animation_progress(partial_frame)
    }

    pub fn trap_switch_x(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.trap[i].switch_pos.x
    }

    pub fn trap_switch_y(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.trap[i].switch_pos.y
    }

    pub fn regular_doors_len(&self) -> usize {
        self.current_sim.entities.doors.regular.len()
    }

    pub fn regular_door_x(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.regular[i].pos.x
    }

    pub fn regular_door_y(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.regular[i].pos.y
    }

    pub fn regular_door_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.doors.regular[i].orientation.rotation_deg()
    }

    pub fn regular_door_anim_progress(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.doors.regular[i].eased_animation_progress(partial_frame)
    }

    pub fn shove_thwumps_len(&self) -> usize {
        self.current_sim.entities.shove_thwumps.len()
    }

    pub fn shove_thwump_x(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.shove_thwumps[i].x(partial_frame)
    }

    pub fn shove_thwump_y(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.shove_thwumps[i].y(partial_frame)
    }

    pub fn shove_thwump_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.shove_thwumps[i].orientation.rotation_deg()
    }

    pub fn shove_thwump_touch(&self, i: usize) -> i32 {
        self.current_sim.entities.shove_thwumps[i].touch_as_num()
    }

    pub fn zap_drones_len(&self) -> usize {
        self.current_sim.entities.zap_drones.len()
    }

    pub fn zap_drone_x(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.zap_drones[i].x(partial_frame)
    }

    pub fn zap_drone_y(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.zap_drones[i].y(partial_frame)
    }

    pub fn zap_drone_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.zap_drones[i].orientation.rotation_deg()
    }

    pub fn chaingun_drones_len(&self) -> usize {
        self.current_sim.entities.chaingun_drones.len()
    }

    pub fn chaingun_drone_x(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.chaingun_drones[i].x(partial_frame)
    }

    pub fn chaingun_drone_y(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.chaingun_drones[i].y(partial_frame)
    }

    pub fn chaingun_drone_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.chaingun_drones[i].orientation.rotation_deg()
    }

    pub fn laser_drones_len(&self) -> usize {
        self.current_sim.entities.laser_drones.len()
    }

    pub fn laser_drone_x(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.laser_drones[i].x(partial_frame)
    }

    pub fn laser_drone_y(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.laser_drones[i].y(partial_frame)
    }

    pub fn laser_drone_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.laser_drones[i].orientation.rotation_deg()
    }

    pub fn chase_drones_len(&self) -> usize {
        self.current_sim.entities.chase_drones.len()
    }

    pub fn chase_drone_x(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.chase_drones[i].x(partial_frame)
    }

    pub fn chase_drone_y(&self, i: usize, partial_frame: f64) -> f64 {
        self.current_sim.entities.chase_drones[i].y(partial_frame)
    }

    pub fn chase_drone_deg(&self, i: usize) -> f64 {
        self.current_sim.entities.chase_drones[i].orientation.rotation_deg()
    }

    pub fn export_attract(&self, editor: &Editor) -> Box<[u8]> {
        MapFile::to_attract(&editor.export_map(), &self.inputs).into()
    }
}

// Separate impl block for functions without #[wasm_bindgen]
impl Replay {
    fn tick_preview(&mut self) {
        if (self.preview_sim.frame as usize) < self.inputs.len() {
            // Save keyframe every 120 frames
            if self.preview_sim.frame.is_multiple_of(120) && !self.keyframes.contains_key(&self.preview_sim.frame) {
                self.keyframes.insert(self.preview_sim.frame, KeyFrame::from_sim(&self.preview_sim, &self.initial_mines));
            }
        }

        if let Some(past_ninja) = self.past_ninjas.get_mut(self.preview_sim.frame as usize) {
            *past_ninja = self.preview_sim.ninja.to_past_ninja();
        } else if self.preview_sim.frame as usize == self.past_ninjas.len() {
            self.past_ninjas.push(self.preview_sim.ninja.to_past_ninja());
        }

        let input = Input::from_byte(self.inputs.get(self.preview_sim.frame as usize).or(self.inputs.last()).cloned().unwrap_or_default());
        self.preview_sim.tick(input, &self.segments);
    }
}

#[cfg(test)]
mod tests {
    use crate::attract::Attract;

    use super::*;

    #[test]
    fn test_seek() {
        let mut replay = Replay::from_attract(include_bytes!("testfiles/762_regression")).unwrap();

        for _ in 0..350 {
            replay.tick();
        }
        replay.seek(123);
        assert_eq!(replay.current_sim.frame, 123);
    }

    #[test]
    fn test_preview_seek() {
        let mut replay = Replay::from_attract(include_bytes!("testfiles/762_regression")).unwrap();

        replay.inputs.truncate(0);

        for i in 0..10 {
            replay.set_input(false, true, false, false);
            assert_eq!(replay.past_ninjas_len(), i);

            replay.tick();
            assert_eq!(replay.past_ninjas_len(), i + 1);

            replay.seek_preview(replay.progress() + 120);

            assert_eq!(replay.progress() + 120, replay.progress_preview());
            assert_eq!(replay.past_ninjas.len(), i + 1 + 120);
        }
    }

    // Replay tests are in separate functions instead of in a loop to make
    // debugging easier.

    #[test]
    fn test_replay_762() {
        let mut replay = Replay::from_attract(include_bytes!("testfiles/762_regression")).unwrap();

        // Each line contains position x and position y separated by a space.
        // One line per frame.
        let nsim_pos_log = include_str!("testfiles/762_poslog.txt");
        let nsim_pos_log = nsim_pos_log
            .split_terminator('\n')
            .map(|string| string
                .split_ascii_whitespace()
                .map(|string| string.parse::<f64>().unwrap())
                .collect::<Vec<f64>>())
            .collect::<Vec<Vec<f64>>>();

        for i in 0..replay.inputs.len() {
            replay.tick();
            if i < nsim_pos_log.len() {
                let x = replay.current_sim.ninja.pos.x;
                let y = replay.current_sim.ninja.pos.y;
                let nsim_x = nsim_pos_log[i][0];
                let nsim_y = nsim_pos_log[i][1];
                let dx = x - nsim_x;
                let dy = y - nsim_y;

                assert!(dx.abs() < 0.000001 && dy.abs() < 0.000001, "{i}");
            }
        }
    }

    #[test]
    fn test_replay_26129() {
        let mut replay = Replay::from_attract(include_bytes!("testfiles/26129_regression")).unwrap();

        // Each line contains position x and position y separated by a space.
        // One line per frame.
        let nsim_pos_log = include_str!("testfiles/26129_poslog.txt");
        let nsim_pos_log = nsim_pos_log
            .split_terminator('\n')
            .map(|string| string
                .split_ascii_whitespace()
                .map(|string| string.parse::<f64>().unwrap())
                .collect::<Vec<f64>>())
            .collect::<Vec<Vec<f64>>>();

        for i in 0..replay.inputs.len() {
            replay.tick();
            if i < nsim_pos_log.len() {
                let x = replay.current_sim.ninja.pos.x;
                let y = replay.current_sim.ninja.pos.y;
                let nsim_x = nsim_pos_log[i][0];
                let nsim_y = nsim_pos_log[i][1];
                let dx = x - nsim_x;
                let dy = y - nsim_y;

                assert!(dx.abs() < 0.000001 && dy.abs() < 0.000001, "{i}");
            }
        }
    }

    impl Replay {
        fn from_attract(attract_bytes: &[u8]) -> Result<Replay, String> {
            let Attract { level_name, author_name, tile_segments, ninjas, entities, inputs, .. } = Attract::from_bytes(attract_bytes)?;

            let mut segments = tile_segments;
            entities.doors.populate_grid(&mut segments);

            let current_sim = Simulation::new(ninjas, entities, false)?;

            let mut keyframes = BTreeMap::new();
            keyframes.insert(0, KeyFrame::from_sim(&current_sim, &current_sim.entities.mines));

            Ok(Replay {
                _level_name: level_name,
                _author_name: Some(author_name),
                segments,
                inputs,
                past_ninjas: Vec::new(),
                initial_mines: current_sim.entities.mines.clone(),
                preview_sim: current_sim.clone(),
                current_sim,
                keyframes,
                sender: None,
                anim_data: Box::new([]),
            })
        }
    }
}
