[package]
name = "ntools-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# convenience crate for sorting floats
float-ord = "0.3.2"
# vector math
glam = { version = "0.30.9", default-features = false, features = ["libm"] }
# bridge to js
wasm-bindgen = "0.2.105"
# random number generation traits
rand = { version = "0.9.0", default-features = false }
# random number generation implementation
rand_xoshiro = "0.7.0"

[profile.release]
lto = "fat"
